"""Generate a runnable Agents SDK project from a ``SystemSpec``."""

from __future__ import annotations

import re

from ..spec import SystemSpec
from .base import env_example, py_str


def _ident(name: str) -> str:
    ident = re.sub(r"\W", "_", name).strip("_") or "item"
    if ident[0].isdigit():
        ident = f"_{ident}"
    return ident


class AgentsPythonBackend:
    name = "agents-python"

    def generate(self, spec: SystemSpec) -> dict[str, str]:
        return {
            "agent_system.py": self._system_py(spec),
            "requirements.txt": "openai-agents>=0.5\n# For non-OpenAI providers:\n# openai-agents[litellm]\n",
            ".env.example": env_example(spec),
            "README.md": self._readme(spec),
        }

    def _system_py(self, spec: SystemSpec) -> str:
        agents_block: list[str] = []
        for agent in spec.agents:
            instructions = f"{agent.role}. Goal: {agent.goal}."
            if agent.backstory:
                instructions += f" {agent.backstory}"
            agents_block.append(
                f"    {py_str(agent.name)}: Agent(\n"
                f"        name={py_str(agent.name)},\n"
                f"        instructions={py_str(instructions)},\n"
                "        output_type=str,\n"
                "    ),"
            )

        tasks_block: list[str] = []
        for task in spec.tasks:
            tasks_block.append(
                "    {\n"
                f'        "id": {py_str(task.id)},\n'
                f'        "description": {py_str(task.description)},\n'
                f'        "agent": {py_str(task.agent)},\n'
                f'        "depends_on": {task.depends_on!r},\n'
                "    },"
            )

        agents_joined = "\n".join(agents_block)
        tasks_joined = "\n".join(tasks_block)
        return f'''"""
{spec.name}: {spec.description}

Generated by the Agents SDK system-factory example (agents-python backend).
Provider-agnostic: set {spec.provider_env} / {spec.model_env} to run against any provider.
"""

from __future__ import annotations

import asyncio

from agents import Agent, Runner

AGENTS: dict[str, Agent] = {{
{agents_joined}
}}

TASKS: list[dict] = [
{tasks_joined}
]


def _waves(tasks: list[dict]) -> list[list[dict]]:
    by_id = {{t["id"]: t for t in tasks}}
    level: dict[str, int] = {{}}

    def resolve(tid: str, stack: frozenset[str]) -> int:
        if tid in level:
            return level[tid]
        if tid in stack:
            raise ValueError(f"cycle at {{tid}}")
        deps = by_id[tid]["depends_on"]
        lvl = 0 if not deps else 1 + max(resolve(d, stack | {{tid}}) for d in deps)
        level[tid] = lvl
        return lvl

    for t in tasks:
        resolve(t["id"], frozenset())
    waves: list[list[dict]] = [[] for _ in range(max(level.values(), default=-1) + 1)]
    for t in tasks:
        waves[level[t["id"]]].append(t)
    return waves


async def run(task_inputs: str = "") -> dict[str, str]:
    results: dict[str, str] = {{}}
    for wave in _waves(TASKS):
        async def _run_one(task: dict) -> tuple[str, str]:
            agent = AGENTS[task["agent"]]
            prompt = task["description"]
            deps = [f"[{{d}}]: {{results[d]}}" for d in task["depends_on"] if d in results]
            if deps:
                prompt += "\\n\\nContext:\\n" + "\\n".join(deps)
            if task_inputs:
                prompt += f"\\n\\nInputs: {{task_inputs}}"
            out = await Runner.run(agent, prompt)
            return task["id"], str(out.final_output)

        for tid, out in await asyncio.gather(*(_run_one(t) for t in wave)):
            results[tid] = out
    return results


if __name__ == "__main__":
    import sys

    outputs = asyncio.run(run(" ".join(sys.argv[1:])))
    for tid, out in outputs.items():
        print(f"\\n===== {{tid}} =====\\n{{out}}")
'''

    def _readme(self, spec: SystemSpec) -> str:
        agent_rows = "\n".join(f"- **{a.name}** — {a.role}: {a.goal}" for a in spec.agents)
        return (
            f"# {spec.name} (Agents SDK)\n\n{spec.description}\n\n"
            "## Agents\n\n" + agent_rows + "\n\n"
            "## Setup\n\n"
            "```bash\n"
            "python -m venv .venv && . .venv/bin/activate  # Windows: .venv\\Scripts\\activate\n"
            "pip install -r requirements.txt\n"
            "cp .env.example .env   # then fill in your keys\n"
            'python agent_system.py "your input here"\n'
            "```\n\n"
            "Provider-agnostic: set "
            f"`{spec.provider_env}` (e.g. `litellm`) and `{spec.model_env}` to target any provider "
            "without an OpenAI key.\n"
        )
