"""Generate a runnable CrewAI project from a ``SystemSpec``."""

from __future__ import annotations

import re

from ..spec import SystemSpec
from .base import env_example, py_str


def _ident(name: str) -> str:
    ident = re.sub(r"\W", "_", name).strip("_") or "item"
    if ident[0].isdigit():
        ident = f"_{ident}"
    return ident


class CrewAIBackend:
    name = "crewai"

    def generate(self, spec: SystemSpec) -> dict[str, str]:
        return {
            "crew.py": self._crew_py(spec),
            "requirements.txt": "crewai>=0.80\npython-dotenv>=1.0\n",
            ".env.example": env_example(spec),
            "README.md": self._readme(spec),
        }

    def _crew_py(self, spec: SystemSpec) -> str:
        lines: list[str] = [
            '"""',
            f"{spec.name}: {spec.description}",
            "",
            "Generated by the Agents SDK system-factory example (CrewAI backend).",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            "import os",
            "",
            "from crewai import Agent, Crew, Process, Task",
            "",
            "",
            "def _llm() -> str | None:",
            f"    # Provider-agnostic: CrewAI routes {'{model}'} through LiteLLM.",
            f"    return os.getenv({py_str(spec.model_env)}) or None",
            "",
            "",
            "def build_crew() -> Crew:",
            "    llm = _llm()",
        ]

        agent_vars: dict[str, str] = {}
        for agent in spec.agents:
            var = f"agent_{_ident(agent.name)}"
            agent_vars[agent.name] = var
            lines += [
                f"    {var} = Agent(",
                f"        role={py_str(agent.role)},",
                f"        goal={py_str(agent.goal)},",
                f"        backstory={py_str(agent.backstory)},",
                "        llm=llm,",
                "        verbose=True,",
                "    )",
            ]

        task_vars: list[str] = []
        by_id = {t.id: t for t in spec.tasks}
        for task in spec.tasks:
            var = f"task_{_ident(task.id)}"
            task_vars.append(var)
            ctx = [f"task_{_ident(d)}" for d in task.depends_on if d in by_id]
            ctx_arg = f"        context=[{', '.join(ctx)}],\n" if ctx else ""
            lines += [
                f"    {var} = Task(",
                f"        description={py_str(task.description)},",
                f"        expected_output={py_str(task.expected_output or 'A useful result.')},",
                f"        agent={agent_vars[task.agent]},",
                ctx_arg + "    )",
            ]

        agents_list = ", ".join(agent_vars.values())
        tasks_list = ", ".join(task_vars)
        lines += [
            "    return Crew(",
            f"        agents=[{agents_list}],",
            f"        tasks=[{tasks_list}],",
            "        process=Process.sequential,",
            "        verbose=True,",
            "    )",
            "",
            "",
            'if __name__ == "__main__":',
            "    result = build_crew().kickoff()",
            "    print(result)",
            "",
        ]
        return "\n".join(lines)

    def _readme(self, spec: SystemSpec) -> str:
        agent_rows = "\n".join(f"- **{a.name}** — {a.role}: {a.goal}" for a in spec.agents)
        return (
            f"# {spec.name} (CrewAI)\n\n{spec.description}\n\n"
            "## Agents\n\n" + agent_rows + "\n\n"
            "## Setup\n\n"
            "```bash\n"
            "python -m venv .venv && . .venv/bin/activate  # Windows: .venv\\Scripts\\activate\n"
            "pip install -r requirements.txt\n"
            "cp .env.example .env   # then fill in your keys\n"
            "python crew.py\n"
            "```\n\n"
            "This project is provider-agnostic: set the model via the "
            f"`{spec.model_env}` env var (any LiteLLM-supported model).\n"
        )
